//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS2GSI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS2GSI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;CS2GSI&quot;
        ///{
        ///    &quot;uri&quot; &quot;http://127.0.0.1:3000&quot;
        ///    &quot;timeout&quot; &quot;2.0&quot;
        ///    &quot;buffer&quot;  &quot;0.0&quot;
        ///    &quot;throttle&quot; &quot;0.1&quot;
        ///    &quot;heartbeat&quot; &quot;60.0&quot;
        ///    &quot;output&quot;
        ///    {
        ///        &quot;precision_time&quot; &quot;3&quot;
        ///        &quot;precision_position&quot; &quot;1&quot;
        ///        &quot;precision_vector&quot; &quot;3&quot;
        ///    }
        ///    &quot;data&quot;
        ///    {
        ///        &quot;provider&quot;            &quot;1&quot;      
        ///        &quot;map&quot;                 &quot;1&quot;
        ///        &quot;round&quot;               &quot;1&quot;
        ///        &quot;player_id&quot;           &quot;1&quot;
        ///        &quot;player_state&quot;        &quot;1&quot;
        ///        &quot;player_match_stats&quot;  &quot;1&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string GSI_CFG_Content {
            get {
                return ResourceManager.GetString("GSI_CFG_Content", resourceCulture);
            }
        }
    }
}
